### ISSUE TITLE
Oddity - Manually Added Magazines

### ISSUE THREAD

**Issue by DarkSir23** [philborman/LazyLibrarian#10]
Not sure what logs to give you with this,... but ever since I added several manual copies to my magazines folder and done a library scan, the titles that I added issues to now have a status of "Skipped" instead of "Show".  I can still browse to the magazine by manually putting in the URL, but the Skipped button isn't clickable.  Any idea what might cause this?

To help with identifying and fixing issues, please include as much information as possible, including:
### Relevant debug log with api keys and any passwords redacted

Please note - usually a single line of log is not sufficient. The lines just before the error occurs can give useful context and greatly assist with debugging.

**Comment by DarkSir23** [comment]
The newest issue DB field was blank for those two entries, and the status had been set to Skipped.  I was able to repopulate those fields manually, and it looks good now.  But thought you'd want to know.

**Comment by philborman** [comment]
I would guess an unrecognised date in the names of the manually added magazine issues. We populate the "newest issue" from the names, trying to match them to the expected format defined in the config file. The "skipped" field is put in when we first add a magazine title to the database, or after an issue is deleted, as at that point we don't know if there are any issues to open. 
The status gets changed to "open" when we add the first issue. I will change it to make sure "open" is set whenever we add an issue.
