### ISSUE TITLE
Won't start

### ISSUE THREAD

**Issue by DarkSir23** [philborman/LazyLibrarian#11]
Getting this:

`
5-Mar-2017 22:49:30 - DEBUG   :: MAIN : (LazyLibrarian) Setup install,versions and commit status
15-Mar-2017 22:49:30 - DEBUG   :: MAIN : (RunGit)Trying to execute: "git rev-parse --abbrev-ref HEAD" with shell in /usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian
15-Mar-2017 22:49:30 - DEBUG   :: MAIN : (RunGit)Git output: [master]
15-Mar-2017 22:49:30 - DEBUG   :: MAIN : (getCurrentGitBranch) Current local branch of repo is [master] 
15-Mar-2017 22:49:30 - DEBUG   :: MAIN : (getInstallType) [git] install detected. Setting Branch to [master]
`

And from the command line:

`
 File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/LazyLibrarian.py", line 241, in <module>
    main()
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/LazyLibrarian.py", line 157, in main
    if not re.match('^[a-z0-9]+$', lazylibrarian.CONFIG['CURRENT_VERSION']):
NameError: global name 're' is not defined
`

This is after latest update.  Hope it helps.

To help with identifying and fixing issues, please include as much information as possible, including:
### Relevant debug log with api keys and any passwords redacted

Please note - usually a single line of log is not sufficient. The lines just before the error occurs can give useful context and greatly assist with debugging.

**Comment by DarkSir23** [comment]
Solved by adding `import re` to the LazyLibrarian.py file :)

**Comment by philborman** [comment]
Yes, trying to fix a problem with windows source installation not knowing
the version number and assuming that it is a locally modified version.

That bit of code used to be in the versioncheck.py file where re is
defined.

Hadn't got round to completing the move last night.
