### ISSUE TITLE
Feature Request -- Magazine Cover Extraction

### ISSUE THREAD

**Issue by DarkSir23** [philborman/LazyLibrarian#5]
I haven't looked into this at ALL yet, but is it possible to add cover extraction for epub, cbr and cbz when scanning magazines?  ghostscript errors out on them currently.  And while not MANY magazines come in epub and cbr format, it's possible.

If you're not familiar with cbr and cbz, they're just RARed and ZIPped collections of images, respectively, for comic book readers.  Beyond me why I'm finding magazines in that format, but there you go :)

To help with identifying and fixing issues, please include as much information as possible, including:
### Relevant debug log with api keys and any passwords redacted

Please note - usually a single line of log is not sufficient. The lines just before the error occurs can give useful context and greatly assist with debugging.

**Comment by philborman** [comment]
I can easily trap non-pdf  for now so ghostscript doesn't complain - just
give a default "nocover" image.
We have a zip parser in lazylibrarian already for reading epub, which are
zip archives but we don't have unrar. I will have to see if there is a
python library we can use. In theory shouldn't be too hard to add. Depends
whats inside the archives and whether there is a standard format to follow,
eg we open the archive and grab page1.jpg , though I doubt if it's going to
be quite that simple.

**Comment by DarkSir23** [comment]
From my experience with CBR and CBZ files, if you pull the first jpg or png, it is usually the cover.  However,you may have to go down one folder in the archive before you find actual jpgs or pngs.

**Comment by philborman** [comment]
Seems there are lots of other options for CBx too with different archivers, eg CB7 for 7zip
Gets a bit complicated then. Also there is no easy unrar option for python, would probably have to be an external program. Im not sure it's worth the effort.

**Comment by DarkSir23** [comment]
To my knowledge, none of them ever gained much traction.  Most comic readers only support cbr and cbz.  I took a look at Mylar, which works with CBR files quite a bit, and it looks like it does indeed rely on a shell command for unrar.  

Epub doable, though? :)

**Comment by philborman** [comment]
Epub and cbz should be doable, do you have links to any examples?
