### ISSUE TITLE
Author Pictures

### ISSUE THREAD

**Issue by DarkSir23** [philborman/LazyLibrarian#7]
If LL doesn't find an image for an author on GoodReads, does it look elsewhere?  I've found two examples where it appears to be using a google image search to find an author's picture, when GoodReads doesn't have one.  These two cases are Mark Williams and Roger Moore.  Neither of these authors are the same person as as the person who comes up with the same name :)

To help with identifying and fixing issues, please include as much information as possible, including:
### Relevant debug log with api keys and any passwords redacted

Please note - usually a single line of log is not sufficient. The lines just before the error occurs can give useful context and greatly assist with debugging.

**Comment by DarkSir23** [comment]
I guess my further question is, would it be possible to add some author tools, like Fix name, change goodreads ID (I know that one would be messy, but helpful in some cases), remove picture, etc.

**Comment by philborman** [comment]
Yes that's exactly what we do. Use the goodreads image if there is one, if
not try a googleimage search on author name and use the first result google
gives us. There might be a better way, I'm open to suggestions :-)

Editing features can be added, but an automated solution would be better.
Actually changing the image is easy, its just a matter if saving the image
you want to use in the cache under the authors authorid, eg 12345678.jpg

**Comment by philborman** [comment]
Added editing feature for authors. If you want to change the image you need to download the new image first, then give the full filename on the edit page. LL will then copy it into it's cache.

Haven't figured out how to get a file selector box working yet so you have to supply the full filename

**Comment by DarkSir23** [comment]
Woot! You're kinda awesome :)

**Comment by philborman** [comment]
<blush/>

LL now has api commands for this too. setAuthorImage  setBookImage
Still no file selector, but you can supply a filename or a url as long as its a jpg or png
Will push to dobytang in a couple of days.

**Comment by DarkSir23** [comment]
Just getting a chance to look at this.  Can't find the edit options for authors.  Are there changes to the style that need to be made?  I'm using Bookstrap

**Comment by DarkSir23** [comment]
Nevermind, I'm blind.
