### ISSUE TITLE
New Author/New Book Status

### ISSUE THREAD

**Issue by DarkSir23** [philborman/LazyLibrarian#8]
New Book status still appears to be applied to newly added authors, so if I have new author status as skipped and new book status as wanted, if I add an author, it's marking all of their books as wanted.

Thanks :)

To help with identifying and fixing issues, please include as much information as possible, including:
### Relevant debug log with api keys and any passwords redacted

Please note - usually a single line of log is not sufficient. The lines just before the error occurs can give useful context and greatly assist with debugging.

**Comment by philborman** [comment]
Yes that was broken inadvertently when the "manual" option was added. I've
fixed it for now but it's about to be changed again when the new series
selections are enabled. Might push an interim release as the series bits
will take a while to finish. Not sure of the best way to do some of it
yet...
