### ISSUE TITLE
Need advice, DBUPGRADE getBookWork

### ISSUE THREAD

**Issue by DarkSir23** [philborman/LazyLibrarian#9]
Since a recent update, LL is choking trying to do update the library:

`08-Mar-2017 20:21:00 - DEBUG   :: DB_UPGRADE : getBookWork: Returning Cached entry for 7268990 Series
08-Mar-2017 20:21:00 - DEBUG   :: DB_UPGRADE : Deleting empty series Insert Title Here 1-3 1-3 1-3 1-3
08-Mar-2017 20:21:00 - DEBUG   :: DB_UPGRADE : getBookWork: Returning Cached entry for 794443 Series
08-Mar-2017 20:21:00 - ERROR   :: DB_UPGRADE : Database error: near "Keepers": syntax error
08-Mar-2017 20:21:00 - ERROR   :: DB_UPGRADE : Database error: near "Keepers": syntax error
08-Mar-2017 20:21:00 - ERROR   :: DB_UPGRADE : Unhandled exception in database update: Traceback (most recent call last):
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/dbupgrade.py", line 548, in dbupgrade
    setSeries(seriesdict, book['BookID'])
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/bookwork.py", line 104, in setSeries
    (item, book['AuthorID']))
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/database.py", line 46, in action
    sqlResult = self.connection.execute(query)
OperationalError: near "Keepers": syntax error
`

Any suggestions where I should look in the database?  I'm guessing it's just hitting something it doesn't expect.  

Every time I restart LL, it tries to update, and then fails, and then never starts its tasks, so it's not searching for wanted books, or anything. :/

To help with identifying and fixing issues, please include as much information as possible, including:
### Relevant debug log with api keys and any passwords redacted

Please note - usually a single line of log is not sufficient. The lines just before the error occurs can give useful context and greatly assist with debugging.

**Comment by philborman** [comment]
I'm guessing that's a trailing apostrophe in the series name Keepers'
Simple fix for now is to edit 
"/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/bookwork.py", line 104, in setSeries `(item, book['AuthorID']))`

change the "item" part  to `(item.replace("'",""), book['AuthorID']))`

I will put a proper fix in the next release. Sorry about that!

**Comment by DarkSir23** [comment]
Looks like it got a bit farther, but this time it doesn't give much indication:

`09-Mar-2017 07:32:32 - DEBUG   :: DB_UPGRADE : getBookWork: Returning Cached entry for 102733 Series
09-Mar-2017 07:32:32 - DEBUG   :: DB_UPGRADE : getBookWork: Returning Cached entry for 23512999 Series
09-Mar-2017 07:32:32 - ERROR   :: DB_UPGRADE : Unhandled exception in database update: Traceback (most recent call last):
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/dbupgrade.py", line 548, in dbupgrade
    setSeries(seriesdict, book['BookID'])
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/lazylibrarian/bookwork.py", line 106, in setSeries
    controlValueDict = {"BookID": bookid, "SeriesID": match['SeriesID']}
TypeError: list indices must be integers, not str
`

**Comment by DarkSir23** [comment]
Ok, turns out that the weridness in Keepers was actually full quotes around the word "Keepers" in the series title.  So I unded the change above and reran, seeing what happens next.  Is the Debug line "Returning Cached entry" going to indicate the book that the error is occurring on, or the book before?

And regarding your "Sorry about that", don't you dare :)  I knew the risks of using this fork.  I'm just happy to help you catch snags. :)

**Comment by philborman** [comment]
Ok, the "returning cached entry" is just saying the page for the book
you're currently working on is already in the cache and not too old, so we
don't need to ask goodreads for it again. The error with quotes in the
title is the problem. We try to add the title to the "series" table, and
fail. The later code assumes it worked, tries to read the value back and
fails. If we fix the first error the rest will go away.

Just added some code to that section to treat series titles the same as
author names where we already process out quotes.
Hopefully this will fix it.

**Comment by DarkSir23** [comment]
Ok, just updated and I'm getting a long line of these:

`09-Mar-2017 11:01:36 - ERROR   :: DB_UPGRADE : Database error: ambiguous column name: AuthorName
09-Mar-2017 11:01:36 - DEBUG   :: DB_UPGRADE : Get Book Work - Invalid bookID [1585349]
09-Mar-2017 11:01:37 - ERROR   :: DB_UPGRADE : Database error: ambiguous column name: AuthorName
09-Mar-2017 11:01:37 - DEBUG   :: DB_UPGRADE : Get Book Work - Invalid bookID [20977397]
`

**Comment by DarkSir23** [comment]
Ok, I'll try again in a little bit :)

**Comment by philborman** [comment]
Might need to be tomorrow now, just running the tests again, made a few more changes for accented characters

**Comment by philborman** [comment]
Should be fixed now, and a bit faster too

**Comment by DarkSir23** [comment]
Looking good :)

**Comment by DarkSir23** [comment]
New one:  Adding an author, I get this:

`10-Mar-2017 14:03:36 - DEBUG   :: ADDAUTHOR : CacheHandler: Storing XML for http://www.goodreads.com/author/list/12121212.xml?key=<key>&page=2
10-Mar-2017 14:03:39 - DEBUG   :: ADDAUTHOR : Found 7 total books for author
10-Mar-2017 14:03:39 - DEBUG   :: ADDAUTHOR : Removed 3 unwanted language results for author
10-Mar-2017 14:03:39 - DEBUG   :: ADDAUTHOR : Removed 0 bad character or no-name results for author
10-Mar-2017 14:03:39 - DEBUG   :: ADDAUTHOR : Removed 1 duplicate result for author
10-Mar-2017 14:03:39 - DEBUG   :: ADDAUTHOR : Found 0 books by author marked as Ignored
10-Mar-2017 14:03:39 - DEBUG   :: ADDAUTHOR : Imported/Updated 3 books for author
10-Mar-2017 14:03:39 - INFO    :: ADDAUTHOR : [Author Name] Book processing complete: Added 3 books to the database
10-Mar-2017 14:03:39 - DEBUG   :: ADDAUTHOR : [Author Name] Author update complete
10-Mar-2017 14:04:05 - DEBUG   :: WEBSERVER : Status set to "Wanted" for "Book Name"
10-Mar-2017 14:04:05 - ERROR   :: SEARCHNZB : Database error: no such column: AuthorName
10-Mar-2017 14:04:05 - ERROR   :: SEARCHNZB : Failed query: [SELECT BookID, AuthorName, BookName, BookSub from books WHERE BookID="11122222" AND books.AuthorID = authors.Author
ID AND books.Status="Wanted"]
`

**Comment by philborman** [comment]
Well spotted. Just fixed that.
